### ISSUE TITLE
Where to buy a new Farmduino?

### ISSUE THREAD

**Issue by Agrartechnik17** [FarmBot/farmbot-arduino-firmware#102]
Yesterday we found out that we will need a new Farmduino.

Searching for a solution about our Problem with getting our Farmbot started we got to this link:

https://forum.farmbot.org/t/message-broker-not-communicating-with-farmbot-failed-to-start-child-enoent/3127

There they are telling that you should buy a new Farmduino if you have such problems. Now I am searching for where to buy a new Farmduino. Maybe you can help me!
Will the new Farmduino be totally set up for using? Or this there further programming required?

**Comment by gabrielburnworth** [comment]
The forum thread you linked to is generally about Arduino, not Farmduino. Before getting a new board,
 * Make sure that other electronics and wiring are not causing the issue.
 * Make sure you are using the latest version of FarmBot OS.

All the software needed is installed with [FarmBot OS](https://software.farm.bot/docs/farmbot-os#section-installing-farmbot-os).

If you would like to buy a Farmduino, they are available at [farm.bot/shop](https://farm.bot/shop/v1-3-farmduino/). [Arduinos](https://farm.bot/shop/arduino-mega-2560/) are also available. If you purchased a kit and are seeking replacement parts, contact support@farm.bot.
