### ISSUE TITLE
Change this repo to 'farmbot-arduino-firmware' ??

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/farmbot-arduino-firmware#28]
What do you think? It might help differentiate it more from 'raspberry-pi-controller'

**Comment by RickCarlino** [comment]
:+1: I think it's a good move. What do you think, @TimEvWw ?

**Comment by TimEvWw** [comment]
It sounds good, but could you hold on until I finished the refactoring?

**Comment by roryaronson** [comment]
Sounds good!
