### ISSUE TITLE
Calibration of paramaters bricks the device

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/farmbot-arduino-firmware#31]
When I use the web app to calibrate the parameters such as max-x-speed, the device no longer moves. Reflashing the Arduino fixes the issue.

**Comment by TimEvWw** [comment]
You mean changing the parameters? Calibration doesn't use max speed.

**Comment by roryaronson** [comment]
Yea that's what I meant

On Wed, Sep 30, 2015, 5:12 AM Tim Evers <notifications@github.com> wrote:

> You mean changing the parameters? Calibration doesn't use max speed.
>
> On Wed, Sep 30, 2015 at 12:22 AM, Rory Aronson <notifications@github.com>
> wrote:
>
> > When I use the web app to calibrate the parameters such as max-x-speed,
> > the device no longer moves. Reflashing the Arduino fixes the issue.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/FarmBot/farmbot-arduino-firmware/issues/31>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FarmBot/farmbot-arduino-firmware/issues/31#issuecomment-144376680>
> .
>
-- 
Rory Aronson
