### ISSUE TITLE
X2 Dont work

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/farmbot-arduino-firmware#42]
I use ![b7465ae-ramps_figure_edit](https://cloud.githubusercontent.com/assets/20598279/21171430/23b6c86c-c1dd-11e6-86ce-30e3f2909b85.png)
X2 dont work
only X1

farmbot-arduino-firmware - latest

**Comment by roryaronson** [comment]
Hi @Daniil145, the support for the second X motor will be available in the next release.

**Comment by Daniil145** [comment]
![zseries_rus](https://cloud.githubusercontent.com/assets/20598279/21183798/a5c08112-c21a-11e6-83c8-f81366268cfe.png) 
I Use this now)

**Comment by fluffy** [comment]
I just ran into this problem too. Any guess on when the version that supports X2 will be ready ?

**Comment by TimEvWw** [comment]
After new year. The code is finished, but needs to be tested before
releasing.

**Comment by fluffy** [comment]
I created a patch to drive the two motors and tested it out and sent a PR for it. Seems to be all working for me. Not sure if it meets coding style etc but have a look at it and glad to edit to bring it in line with whatever want.

**Comment by TimEvWw** [comment]
The version with X2 is released. That version includes enabling the motor with EEPROM parameters.
