### ISSUE TITLE
GetCodeEnum () is always equal to CODE_UNDEFINED

### ISSUE THREAD

**Issue by linqingfeng** [FarmBot/farmbot-arduino-firmware#45]
Hi,

We used the last stable version "Version 2.0.0 (Biennial Bignonia)" to use the serial debugging tool to test the send instruction is valid, but the latest code to compile will not work, do not know why?

We will open the code of the log, found getCodeEnum () is always equal to CODE_UNDEFINED, what is the reason?

thank you very much!

**Comment by TimEvWw** [comment]
A code like G00 should work. What is the exact command sent to the firmware?
