### ISSUE TITLE
Support G codes in mm

### ISSUE THREAD

**Issue by fluffy** [FarmBot/farmbot-arduino-firmware#46]
It seems like it would be nice if the G codes could be sent to the Arduino with the units in mm and for the Arduino to have a EEPROM stored configuration parameters with the conversion of mm to pulses with separate conversion factors for X, Y, and Z. 

Perhaps I have just missed how this is all supposed to work as I am still getting up to speed on it.

**Comment by TimEvWw** [comment]
Moving in mm is now implemented on the GUI
