### ISSUE TITLE
Motor X2 not working

### ISSUE THREAD

**Issue by AscendFB** [FarmBot/farmbot-arduino-firmware#54]
Hello everyone,

my second motor on X-Axis is still not working at all. Using the newest firmware.
What I tried so far:
- update via staging.farmbot.io
- upload directly to arduino
- versions a few commits earlier

Uploading the dual motor version of fluffy helps out, but i think it may be outdated since its from mid December. 

Is there anything needed to be done manually to get the X2 motor running? Or is it just activated by default?

Also there are sometimes messages from arduino, just like this:
![image](https://cloud.githubusercontent.com/assets/23129562/22605506/69970824-ea50-11e6-855a-1ef9aee6c025.png)
but they appear for every axis.

**Comment by TimEvWw** [comment]
Can confirm there is a bug for X2. Working on it.

**Comment by vaibhavgupta3110** [comment]
Added the E parameters to the farmbot_arduino_controller.cpp file and it's confirmed working perfectly, you can test out the config from this PR

#55

**Comment by roryaronson** [comment]
Hooray!
