### ISSUE TITLE
Dont work endpoint after update

### ISSUE THREAD

**Issue by Daniil145** [FarmBot/farmbot-arduino-firmware#62]
I use whis version
Endpoints dont work
![7777](https://cloud.githubusercontent.com/assets/20598279/23998624/aea3b648-0a66-11e7-82f1-c57109ef6f07.PNG)

**Comment by RickCarlino** [comment]
@Daniil145 It looks like you're running an old version of the frontend. Firmware and FBOS are no longer updated separately.

Please update your API and run `./install_frontend.sh`.

Also, make sure that you run `ctrl + shift + r` to clear your browser cache (in case your browser has an old version in cache).

It should look like this:

![image](https://cloud.githubusercontent.com/assets/1388608/24001849/305b5dd8-0a2d-11e7-9f60-dfc36bab6859.png)

**Comment by Daniil145** [comment]
Endpoints work on new version?

**Comment by Daniil145** [comment]
![image](https://cloud.githubusercontent.com/assets/20598279/24019033/71cd8a64-0aa7-11e7-8ea5-197c1e574d5b.png)
I updated and test it tommorow
