### ISSUE TITLE
Wont compile

### ISSUE THREAD

**Issue by kezzab25** [FarmBot/farmbot-arduino-firmware#99]
It had a few issues when I first compiled. One was defining NULL and others were something about long ints? I had to change a few 0.0 to 0 to make it compile. Why was this?
I managed to make a few changes and now it compiles but I cant remember what I changed.

**Comment by gabrielburnworth** [comment]
Do you have Mega 2560 selected as the board to compile for? What version of the Arduino IDE are you using?

**Comment by kezzab25** [comment]
I am using 1.8.1 and yes I have mega 2560 selected. It uploads fine once I
fix the errors. I'm just wondering why I'm getting errors in the first
place?

On 26 Feb. 2018 7:27 pm, "Gabriel Burnworth" <notifications@github.com>
wrote:

Do you have Mega 2560 selected as the board to compile for? What version of
the Arduino IDE are you using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FarmBot/farmbot-arduino-firmware/issues/99#issuecomment-368402986>,
or mute the thread

**Comment by gabrielburnworth** [comment]
I am using `Arduino 1.8.1` and `Mega 2560` and I don't get any compile errors on `3ad1d88`.

You can try:
```
git clone -b 'v6.0.1' --single-branch  https://github.com/FarmBot/farmbot-arduino-firmware
```

**Comment by kezzab25** [comment]
![farmbot20180226_195106](https://user-images.githubusercontent.com/4483969/36656908-45d4fcaa-1b2f-11e8-81de-e760d089747b.jpg)

**Comment by kezzab25** [comment]
Sorry, the one that wont compile is version 1.8.4

**Comment by gabrielburnworth** [comment]
Ah, those are complier warnings, not errors. The build should still compile successfully. Do you not get `Done compiling.`?

**Comment by kezzab25** [comment]
I was a bit impatient. It does eventually upload if I wait a bit longer
